import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "de" | "fr" | "ar" | "zh" | "pl" | "tr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "nav.home": "Home",
    "nav.ecosystem": "Ecosystem",
    "nav.projects": "Projects",
    "nav.automation": "Automation",
    "nav.contact": "Contact",
    
    // Hero
    "hero.title": "AI Byte Consult Ltd",
    "hero.subtitle": "The Future of Intelligent Business Systems",
    "hero.description": "A global technology company specializing in AI development and business automation. We design intelligent systems for enterprises, hospitality, healthcare, logistics, and research — empowering organizations worldwide through innovation.",
    "hero.cta": "Explore Ecosystem",
    
    // About
    "about.title": "About the Company",
    "about.p1": "AI Byte Consult Ltd. is a global technology company specializing in artificial intelligence and automation. We design intelligent systems that optimize operations, enhance decision-making, and accelerate digital transformation for organizations worldwide.",
    "about.p2": "Our AI-driven solutions serve diverse industries — from B2B and B2C enterprises to hospitality, healthcare, logistics, geology, and scientific research. We build scalable platforms that help businesses automate workflows, analyze data efficiently, and unlock new opportunities through intelligent innovation.",
    
    // Ecosystem
    "ecosystem.title": "Our Ecosystem",
    "ecosystem.subtitle": "A comprehensive suite of AI-powered solutions for the modern digital economy",
    "ecosystem.nics.title": "NICS AI Ecosystem",
    "ecosystem.nics.desc": "NICS AI Ecosystem is a unified artificial intelligence and blockchain infrastructure designed to connect industries, automate workflows, and enable cross-platform data synchronization. It combines decentralized logic, neural APIs, and tokenized access to deliver secure, scalable, and intelligent solutions for businesses, developers, and global communities.",
    "ecosystem.horeca.title": "NICS AI HoReCa",
    "ecosystem.horeca.desc": "NICS AI HoReCa is an advanced AI automation platform for restaurants, bars, and cafés. It provides White Label solutions with voice-driven interaction, smart analytics, order automation, and adaptive AI agents. Integrated with POS, CRM, and payment systems, it streamlines hospitality operations and enhances customer experience through intelligent automation.",
    "ecosystem.geologist.title": "NICS AI Geologist",
    "ecosystem.geologist.desc": "NICS AI Geologist is an analytical platform connecting geology, mining, and genealogy through intelligent data fusion. It processes exploration data, geological layers, and historical archives to identify resource potential and ancestral land correlations. The system supports sustainable exploration and digital heritage mapping with AI-powered insight.",
    "ecosystem.aquaterra.title": "AquaTerra World (Metaverse)",
    "ecosystem.aquaterra.desc": "AquaTerra World is an immersive AI-driven metaverse that unites virtual collaboration, entertainment, and business innovation. Within this 3D environment, users interact, learn, and trade using digital assets powered by AI and blockchain, creating a seamless connection between virtual experience and real-world economy.",
    "ecosystem.pantheon.title": "Pantheon of Eternals",
    "ecosystem.pantheon.desc": "Pantheon of Eternals AI is a revolutionary collection of interactive iNFT entities inspired by ancient mythology. Each Eternal—whether Zeus, Ra, or Odin—is reborn as an AI avatar with personality, dialogue, and adaptive learning. Merging divine archetypes with artificial intelligence, the Pantheon bridges storytelling, identity, and digital evolution.",
    "ecosystem.pride.title": "PRIDE Social Network",
    "ecosystem.pride.desc": "PRIDE Social Network is a decentralized Web3 community platform that rewards creativity and engagement with native tokens. It empowers users to share ideas, art, and experiences while earning from their social activity, building an inclusive and self-sustaining digital ecosystem for expression and collaboration.",
    
    // Projects
    "projects.title": "Our Work in Action",
    "projects.subtitle": "Real solutions delivering measurable results for forward-thinking businesses",
    "projects.restaurant.title": "Restaurant Chain Automation",
    "projects.restaurant.desc": "Smart ordering and AI customer service for TasteWave Bistro. Increased efficiency by 150%.",
    "projects.logistics.title": "Logistics Parser AI",
    "projects.logistics.desc": "Real-time supply chain tracking for CargoNova with predictive analytics.",
    "projects.hotel.title": "Hotel Booking Automation",
    "projects.hotel.desc": "WhatsApp chatbot integration for OceanView Resorts with seamless booking experience.",
    "projects.nft.title": "NFT Intelligence Framework",
    "projects.nft.desc": "AI-based artifact creation system for Eternals by Nixie with voice synthesis.",
    "projects.clinic.title": "Voice Assistant for Clinics",
    "projects.clinic.desc": "Appointment automation for MediCore Health with natural language processing.",
    "projects.retail.title": "Retail Analytics Platform",
    "projects.retail.desc": "AI-driven sales prediction for UrbanMarket with inventory optimization.",
    
    // Automation Constructor
    "constructor.title": "Automation Constructor",
    "constructor.subtitle": "Design your custom AI automation in minutes — choose your platform, model, and role.",
    "constructor.step1": "Select Platform",
    "constructor.step2": "Choose AI Model",
    "constructor.step3": "Define Your Task",
    "constructor.step4": "Select Automation Type",
    "constructor.step5": "Integration Setup",
    "constructor.step5.desc": "Choose how your AI automation connects with external systems — databases, APIs, or webhooks. If you're unsure, you can skip this step.",
    "constructor.step6": "Review & Submit",
    "constructor.task.placeholder": "Describe what your automation should do...",
    "constructor.contact.title": "Contact Information",
    "constructor.contact.desc": "Please enter at least one way to reach you:",
    "constructor.skip": "💡 Not sure? Choose later",
    "constructor.back": "Back",
    "constructor.next": "Next",
    "constructor.submit": "Submit Order",
    "constructor.success": "✅ Request sent successfully! We will contact you soon.",
    "constructor.error.platform": "Please select a platform",
    "constructor.error.model": "Please select an AI model",
    "constructor.error.task": "Please describe your task",
    "constructor.error.role": "Please select automation type",
    "constructor.error.contact": "Please enter at least one contact method.",
    
    // AI Automation Fix
    "aifix.title": "AI Automation Fix",
    "aifix.subtitle": "AI-Powered Business Automation for Global Companies",
    "aifix.intro1": "AI ByteConsult Ltd is a global technology company specializing in AI-powered business automation, intelligent systems, and advanced workflow automation for companies across enterprise, hospitality, healthcare, and service industries.",
    "aifix.intro2": "Our flagship solution, AI Automation Fix, is designed to automate one core business process quickly and efficiently, delivering measurable results within 1–3 business days.",
    "aifix.included": "What's Included",
    "aifix.included.1": "Quick automation audit (20–30 minutes)",
    "aifix.included.2": "Automation of one high-impact business process",
    "aifix.included.3": "AI-powered workflows and system integrations",
    "aifix.included.4": "Documentation and optional ongoing support",
    "aifix.benefits": "Business Benefits",
    "aifix.benefits.1": "Reduced manual workload",
    "aifix.benefits.2": "Faster lead and customer response times",
    "aifix.benefits.3": "Improved operational efficiency",
    "aifix.benefits.4": "Scalable AI-driven processes",
    "aifix.pricing": "Example Pricing",
    "aifix.pricing.audit": "Automation Audit",
    "aifix.pricing.impl": "Implementation",
    "aifix.pricing.support": "Monthly Support",
    "aifix.usecases": "Typical Automation Use Cases",
    "aifix.usecase.lead": "AI Lead Handler",
    "aifix.usecase.lead.desc": "Intake, qualification, routing",
    "aifix.usecase.sales": "AI Sales Assistant",
    "aifix.usecase.sales.desc": "Prospect qualification & support",
    "aifix.usecase.content": "AI Content Engine",
    "aifix.usecase.content.desc": "Automated content workflows",
    "aifix.usecase.support": "AI Support Agent",
    "aifix.usecase.support.desc": "24/7 customer assistance",
    "aifix.usecase.owner": "AI Owner Assistant",
    "aifix.usecase.owner.desc": "Internal summaries & insights",
    "aifix.howitworks": "How It Works",
    "aifix.step1": "Discovery call to understand your workflow",
    "aifix.step2": "Identification of the highest-impact automation",
    "aifix.step3": "Build and deployment using AI, APIs, and automation platforms",
    "aifix.step4": "Delivery, documentation, and optional support",
    "aifix.cta.title": "Ready to automate your business with AI?",
    "aifix.cta.subtitle": "Book an automation audit or contact our team to get started.",
    "aifix.cta.button": "Get Started Now",
    
    // Testimonials
    "testimonials.title": "Trusted by Innovators",
    "testimonials.subtitle": "See what our clients say about working with us",
    "testimonials.1.quote": "AI Byte Consult revolutionized our logistics operations. The real-time tracking system has saved us countless hours and improved our delivery accuracy by 95%.",
    "testimonials.1.author": "Maria Lopez",
    "testimonials.1.position": "CEO, CargoNova",
    "testimonials.2.quote": "Their automation system doubled our restaurant efficiency. We're now serving more customers with better accuracy and happier staff.",
    "testimonials.2.author": "David Chen",
    "testimonials.2.position": "Founder, TasteWave Bistro",
    "testimonials.3.quote": "Our NFT launch became truly intelligent thanks to their AI layer. The voice-enabled avatars created an entirely new level of engagement.",
    "testimonials.3.author": "Elena Rossi",
    "testimonials.3.position": "NFT Project Lead",
    
    // Team
    "team.title": "Meet the Founders",
    "team.subtitle": "The visionaries behind AI Byte Consult Ltd.",
    "team.alex.name": "Alexander Lunin",
    "team.alex.role": "Co-Founder & AI Architect",
    "team.alex.bio": "Leads AI architecture and Web3 integrations across the Nixie Ecosystem. Over 15 years of experience in cutting-edge technology.",
    "team.aleksandr.name": "Aleksandr Tochilov",
    "team.aleksandr.role": "Co-Founder & Product Director",
    "team.aleksandr.bio": "Focuses on automation systems, client solutions, and creative ecosystem design. Passionate about turning complex tech into simple solutions.",
    
    // Contact
    "contact.title": "Get in Touch",
    "contact.subtitle": "Let's build the future of automation together",
    "contact.name": "Name",
    "contact.name.placeholder": "Your name",
    "contact.email": "Email",
    "contact.email.placeholder": "your.email@example.com",
    "contact.message": "Message",
    "contact.message.placeholder": "Tell us about your project...",
    "contact.submit": "Send Message",
    "contact.success": "Message sent! We'll get back to you soon.",
    
    // Newsletter
    "newsletter.title": "Stay Updated",
    "newsletter.subtitle": "Join our innovation updates and be the first to know about new features and insights",
    "newsletter.placeholder": "your.email@example.com",
    "newsletter.submit": "Subscribe",
    "newsletter.success": "Thanks for subscribing to our newsletter!",
    
    // Footer
    "footer.description": "Intelligent Automation, Blockchain & Web3 Solutions — building the future of business technology within the NICS AI Ecosystem.",
    "footer.quicklinks": "Quick Links",
    "footer.home": "Home",
    "footer.ecosystem": "Ecosystem",
    "footer.projects": "Projects",
    "footer.contact": "Contact",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.copyright": "AI Byte Consult Ltd. All rights reserved.",
    
    // Telegram Products
    "products.badge": "Starter Packages",
    "products.title": "Telegram Solutions",
    "products.subtitle": "Professional Telegram tools to boost your business presence and automate customer interactions",
    "products.oneTime": "one-time",
    "products.buyNow": "Buy Now",
    "products.note": "Secure payment via Revolut. Delivery within 1-3 business days.",
    
    "products.card.title": "Digital Card",
    "products.card.subtitle": "Telegram Business Card",
    "products.card.description": "A professional digital business card bot that showcases your services, contact info, and social links in an elegant Telegram interface.",
    "products.card.feature1": "Custom branded design",
    "products.card.feature2": "Contact & social links",
    "products.card.feature3": "Service showcase",
    "products.card.feature4": "Easy sharing via link",
    
    "products.bot.title": "Menu Bot",
    "products.bot.subtitle": "Telegram Group Bot",
    "products.bot.description": "A smart bot for your Telegram group with interactive menu, automated responses, and moderation tools to engage your community.",
    "products.bot.feature1": "Interactive menu system",
    "products.bot.feature2": "Automated welcome messages",
    "products.bot.feature3": "Basic moderation tools",
    "products.bot.feature4": "Custom commands",
    
    "products.ai.title": "AI Assistant",
    "products.ai.subtitle": "AI-Powered Group Bot",
    "products.ai.description": "An intelligent AI bot for groups with product catalog, smart responses, and conversational AI to handle customer inquiries automatically.",
    "products.ai.feature1": "AI-powered chat responses",
    "products.ai.feature2": "Product catalog display",
    "products.ai.feature3": "Order inquiry handling",
    "products.ai.feature4": "Multi-language support",
  },
  de: {
    // Header
    "nav.home": "Startseite",
    "nav.ecosystem": "Ökosystem",
    "nav.projects": "Projekte",
    "nav.automation": "Automatisierung",
    "nav.contact": "Kontakt",
    
    // Hero
    "hero.title": "AI Byte Consult Ltd",
    "hero.subtitle": "Die Zukunft intelligenter Geschäftssysteme",
    "hero.description": "Ein globales Technologieunternehmen, spezialisiert auf KI-Entwicklung und Geschäftsautomatisierung. Wir entwickeln intelligente Systeme für Unternehmen, Gastgewerbe, Gesundheitswesen, Logistik und Forschung — und stärken Organisationen weltweit durch Innovation.",
    "hero.cta": "Ökosystem erkunden",
    
    // About
    "about.title": "Über das Unternehmen",
    "about.p1": "AI Byte Consult Ltd. ist ein globales Technologieunternehmen, das sich auf künstliche Intelligenz und Automatisierung spezialisiert hat. Wir entwickeln intelligente Systeme, die Abläufe optimieren, Entscheidungsfindung verbessern und die digitale Transformation für Organisationen weltweit beschleunigen.",
    "about.p2": "Unsere KI-gesteuerten Lösungen bedienen verschiedene Branchen — von B2B- und B2C-Unternehmen bis hin zu Gastgewerbe, Gesundheitswesen, Logistik, Geologie und wissenschaftlicher Forschung. Wir bauen skalierbare Plattformen, die Unternehmen helfen, Arbeitsabläufe zu automatisieren, Daten effizient zu analysieren und neue Möglichkeiten durch intelligente Innovation zu erschließen.",
    
    // Ecosystem
    "ecosystem.title": "Unser Ökosystem",
    "ecosystem.subtitle": "Eine umfassende Suite KI-gestützter Lösungen für die moderne digitale Wirtschaft",
    "ecosystem.nics.title": "NICS AI Ökosystem",
    "ecosystem.nics.desc": "Das NICS AI Ökosystem ist eine vereinheitlichte Infrastruktur für künstliche Intelligenz und Blockchain, die Branchen verbindet, Arbeitsabläufe automatisiert und plattformübergreifende Datensynchronisation ermöglicht.",
    "ecosystem.horeca.title": "NICS AI HoReCa",
    "ecosystem.horeca.desc": "NICS AI HoReCa ist eine fortschrittliche KI-Automatisierungsplattform für Restaurants, Bars und Cafés. Sie bietet White-Label-Lösungen mit sprachgesteuerten Interaktionen, intelligenten Analysen und Bestellautomatisierung.",
    "ecosystem.geologist.title": "NICS AI Geologe",
    "ecosystem.geologist.desc": "NICS AI Geologe ist eine analytische Plattform, die Geologie, Bergbau und Genealogie durch intelligente Datenfusion verbindet.",
    "ecosystem.aquaterra.title": "AquaTerra World (Metaverse)",
    "ecosystem.aquaterra.desc": "AquaTerra World ist ein immersives, KI-gesteuertes Metaverse, das virtuelle Zusammenarbeit, Unterhaltung und Geschäftsinnovation vereint.",
    "ecosystem.pantheon.title": "Pantheon der Ewigen",
    "ecosystem.pantheon.desc": "Pantheon of Eternals AI ist eine revolutionäre Sammlung interaktiver iNFT-Entitäten, inspiriert von antiker Mythologie.",
    "ecosystem.pride.title": "PRIDE Soziales Netzwerk",
    "ecosystem.pride.desc": "PRIDE Social Network ist eine dezentrale Web3-Community-Plattform, die Kreativität und Engagement mit nativen Token belohnt.",
    
    // Projects
    "projects.title": "Unsere Arbeit in Aktion",
    "projects.subtitle": "Echte Lösungen mit messbaren Ergebnissen für zukunftsorientierte Unternehmen",
    "projects.restaurant.title": "Restaurantketten-Automatisierung",
    "projects.restaurant.desc": "Intelligente Bestellung und KI-Kundenservice für TasteWave Bistro. Effizienzsteigerung um 150%.",
    "projects.logistics.title": "Logistik-Parser KI",
    "projects.logistics.desc": "Echtzeit-Lieferkettenverfolgung für CargoNova mit prädiktiver Analytik.",
    "projects.hotel.title": "Hotel-Buchungsautomatisierung",
    "projects.hotel.desc": "WhatsApp-Chatbot-Integration für OceanView Resorts mit nahtloser Buchungserfahrung.",
    "projects.nft.title": "NFT-Intelligenz-Framework",
    "projects.nft.desc": "KI-basiertes Artefakt-Erstellungssystem für Eternals by Nixie mit Sprachsynthese.",
    "projects.clinic.title": "Sprachassistent für Kliniken",
    "projects.clinic.desc": "Terminautomatisierung für MediCore Health mit natürlicher Sprachverarbeitung.",
    "projects.retail.title": "Einzelhandels-Analyseplattform",
    "projects.retail.desc": "KI-gesteuerte Verkaufsprognose für UrbanMarket mit Bestandsoptimierung.",
    
    // Automation Constructor
    "constructor.title": "Automatisierungs-Konfigurator",
    "constructor.subtitle": "Gestalten Sie Ihre individuelle KI-Automatisierung in Minuten — wählen Sie Plattform, Modell und Rolle.",
    "constructor.step1": "Plattform wählen",
    "constructor.step2": "KI-Modell wählen",
    "constructor.step3": "Aufgabe definieren",
    "constructor.step4": "Automatisierungstyp wählen",
    "constructor.step5": "Integrations-Setup",
    "constructor.step5.desc": "Wählen Sie, wie Ihre KI-Automatisierung mit externen Systemen verbunden wird — Datenbanken, APIs oder Webhooks.",
    "constructor.step6": "Überprüfen & Absenden",
    "constructor.task.placeholder": "Beschreiben Sie, was Ihre Automatisierung tun soll...",
    "constructor.contact.title": "Kontaktinformationen",
    "constructor.contact.desc": "Bitte geben Sie mindestens eine Kontaktmöglichkeit an:",
    "constructor.skip": "💡 Nicht sicher? Später wählen",
    "constructor.back": "Zurück",
    "constructor.next": "Weiter",
    "constructor.submit": "Bestellung absenden",
    "constructor.success": "✅ Anfrage erfolgreich gesendet! Wir werden Sie bald kontaktieren.",
    "constructor.error.platform": "Bitte wählen Sie eine Plattform",
    "constructor.error.model": "Bitte wählen Sie ein KI-Modell",
    "constructor.error.task": "Bitte beschreiben Sie Ihre Aufgabe",
    "constructor.error.role": "Bitte wählen Sie einen Automatisierungstyp",
    "constructor.error.contact": "Bitte geben Sie mindestens eine Kontaktmöglichkeit an.",
    
    // AI Automation Fix
    "aifix.title": "AI Automation Fix",
    "aifix.subtitle": "KI-gestützte Geschäftsautomatisierung für globale Unternehmen",
    "aifix.intro1": "AI ByteConsult Ltd ist ein globales Technologieunternehmen, das sich auf KI-gestützte Geschäftsautomatisierung, intelligente Systeme und fortschrittliche Workflow-Automatisierung für Unternehmen in den Bereichen Enterprise, Gastgewerbe, Gesundheitswesen und Dienstleistungen spezialisiert hat.",
    "aifix.intro2": "Unsere Flaggschiff-Lösung, AI Automation Fix, ist darauf ausgelegt, einen Kerngeschäftsprozess schnell und effizient zu automatisieren und messbare Ergebnisse innerhalb von 1–3 Werktagen zu liefern.",
    "aifix.included": "Was enthalten ist",
    "aifix.included.1": "Schnelles Automatisierungs-Audit (20–30 Minuten)",
    "aifix.included.2": "Automatisierung eines wirkungsvollen Geschäftsprozesses",
    "aifix.included.3": "KI-gestützte Workflows und Systemintegrationen",
    "aifix.included.4": "Dokumentation und optionale laufende Unterstützung",
    "aifix.benefits": "Geschäftsvorteile",
    "aifix.benefits.1": "Reduzierte manuelle Arbeitslast",
    "aifix.benefits.2": "Schnellere Reaktionszeiten für Leads und Kunden",
    "aifix.benefits.3": "Verbesserte betriebliche Effizienz",
    "aifix.benefits.4": "Skalierbare KI-gesteuerte Prozesse",
    "aifix.pricing": "Beispielpreise",
    "aifix.pricing.audit": "Automatisierungs-Audit",
    "aifix.pricing.impl": "Implementierung",
    "aifix.pricing.support": "Monatlicher Support",
    "aifix.usecases": "Typische Automatisierungsanwendungen",
    "aifix.usecase.lead": "KI-Lead-Handler",
    "aifix.usecase.lead.desc": "Aufnahme, Qualifizierung, Weiterleitung",
    "aifix.usecase.sales": "KI-Verkaufsassistent",
    "aifix.usecase.sales.desc": "Interessenten-Qualifizierung & Support",
    "aifix.usecase.content": "KI-Content-Engine",
    "aifix.usecase.content.desc": "Automatisierte Content-Workflows",
    "aifix.usecase.support": "KI-Support-Agent",
    "aifix.usecase.support.desc": "24/7 Kundenbetreuung",
    "aifix.usecase.owner": "KI-Owner-Assistent",
    "aifix.usecase.owner.desc": "Interne Zusammenfassungen & Einblicke",
    "aifix.howitworks": "So funktioniert es",
    "aifix.step1": "Entdeckungsgespräch zum Verständnis Ihres Workflows",
    "aifix.step2": "Identifikation der wirkungsvollsten Automatisierung",
    "aifix.step3": "Aufbau und Bereitstellung mit KI, APIs und Automatisierungsplattformen",
    "aifix.step4": "Lieferung, Dokumentation und optionaler Support",
    "aifix.cta.title": "Bereit, Ihr Geschäft mit KI zu automatisieren?",
    "aifix.cta.subtitle": "Buchen Sie ein Automatisierungs-Audit oder kontaktieren Sie unser Team.",
    "aifix.cta.button": "Jetzt starten",
    
    // Testimonials
    "testimonials.title": "Von Innovatoren vertraut",
    "testimonials.subtitle": "Erfahren Sie, was unsere Kunden über die Zusammenarbeit mit uns sagen",
    "testimonials.1.quote": "AI Byte Consult hat unsere Logistikoperationen revolutioniert. Das Echtzeit-Tracking-System hat uns unzählige Stunden gespart und unsere Liefergenauigkeit um 95% verbessert.",
    "testimonials.1.author": "Maria Lopez",
    "testimonials.1.position": "CEO, CargoNova",
    "testimonials.2.quote": "Ihr Automatisierungssystem hat die Effizienz unseres Restaurants verdoppelt. Wir bedienen jetzt mehr Kunden mit besserer Genauigkeit und zufriedenerem Personal.",
    "testimonials.2.author": "David Chen",
    "testimonials.2.position": "Gründer, TasteWave Bistro",
    "testimonials.3.quote": "Unser NFT-Launch wurde dank ihrer KI-Schicht wirklich intelligent. Die sprachgesteuerten Avatare schufen ein völlig neues Maß an Engagement.",
    "testimonials.3.author": "Elena Rossi",
    "testimonials.3.position": "NFT-Projektleiterin",
    
    // Team
    "team.title": "Lernen Sie die Gründer kennen",
    "team.subtitle": "Die Visionäre hinter AI Byte Consult Ltd.",
    "team.alex.name": "Alexander Lunin",
    "team.alex.role": "Mitgründer & KI-Architekt",
    "team.alex.bio": "Leitet die KI-Architektur und Web3-Integrationen im gesamten Nixie-Ökosystem. Über 15 Jahre Erfahrung in Spitzentechnologie.",
    "team.aleksandr.name": "Aleksandr Tochilov",
    "team.aleksandr.role": "Mitgründer & Produktdirektor",
    "team.aleksandr.bio": "Konzentriert sich auf Automatisierungssysteme, Kundenlösungen und kreatives Ökosystem-Design. Leidenschaftlich daran interessiert, komplexe Technologie in einfache Lösungen umzuwandeln.",
    
    // Contact
    "contact.title": "Kontakt aufnehmen",
    "contact.subtitle": "Lassen Sie uns gemeinsam die Zukunft der Automatisierung gestalten",
    "contact.name": "Name",
    "contact.name.placeholder": "Ihr Name",
    "contact.email": "E-Mail",
    "contact.email.placeholder": "ihre.email@beispiel.de",
    "contact.message": "Nachricht",
    "contact.message.placeholder": "Erzählen Sie uns von Ihrem Projekt...",
    "contact.submit": "Nachricht senden",
    "contact.success": "Nachricht gesendet! Wir melden uns bald bei Ihnen.",
    
    // Newsletter
    "newsletter.title": "Bleiben Sie informiert",
    "newsletter.subtitle": "Abonnieren Sie unsere Innovations-Updates und erfahren Sie als Erster von neuen Funktionen und Einblicken",
    "newsletter.placeholder": "ihre.email@beispiel.de",
    "newsletter.submit": "Abonnieren",
    "newsletter.success": "Danke für Ihre Newsletter-Anmeldung!",
    
    // Footer
    "footer.description": "Intelligente Automatisierung, Blockchain & Web3-Lösungen — wir bauen die Zukunft der Geschäftstechnologie im NICS AI Ökosystem.",
    "footer.quicklinks": "Schnelllinks",
    "footer.home": "Startseite",
    "footer.ecosystem": "Ökosystem",
    "footer.projects": "Projekte",
    "footer.contact": "Kontakt",
    "footer.legal": "Rechtliches",
    "footer.privacy": "Datenschutzrichtlinie",
    "footer.terms": "Nutzungsbedingungen",
    "footer.copyright": "AI Byte Consult Ltd. Alle Rechte vorbehalten.",
    
    // Telegram Products
    "products.badge": "Starter-Pakete",
    "products.title": "Telegram-Lösungen",
    "products.subtitle": "Professionelle Telegram-Tools zur Stärkung Ihrer Geschäftspräsenz und Automatisierung von Kundeninteraktionen",
    "products.oneTime": "einmalig",
    "products.buyNow": "Jetzt kaufen",
    "products.note": "Sichere Zahlung über Revolut. Lieferung innerhalb von 1-3 Werktagen.",
    
    "products.card.title": "Digitale Karte",
    "products.card.subtitle": "Telegram Visitenkarte",
    "products.card.description": "Ein professioneller digitaler Visitenkarten-Bot, der Ihre Dienstleistungen, Kontaktdaten und Social-Links in einer eleganten Telegram-Oberfläche präsentiert.",
    "products.card.feature1": "Individuelles Markendesign",
    "products.card.feature2": "Kontakt- & Social-Links",
    "products.card.feature3": "Dienstleistungsübersicht",
    "products.card.feature4": "Einfaches Teilen per Link",
    
    "products.bot.title": "Menü-Bot",
    "products.bot.subtitle": "Telegram Gruppen-Bot",
    "products.bot.description": "Ein intelligenter Bot für Ihre Telegram-Gruppe mit interaktivem Menü, automatisierten Antworten und Moderationstools zur Community-Bindung.",
    "products.bot.feature1": "Interaktives Menüsystem",
    "products.bot.feature2": "Automatische Willkommensnachrichten",
    "products.bot.feature3": "Basis-Moderationstools",
    "products.bot.feature4": "Benutzerdefinierte Befehle",
    
    "products.ai.title": "KI-Assistent",
    "products.ai.subtitle": "KI-gesteuerter Gruppen-Bot",
    "products.ai.description": "Ein intelligenter KI-Bot für Gruppen mit Produktkatalog, smarten Antworten und konversationeller KI zur automatischen Bearbeitung von Kundenanfragen.",
    "products.ai.feature1": "KI-gestützte Chat-Antworten",
    "products.ai.feature2": "Produktkatalog-Anzeige",
    "products.ai.feature3": "Bestellanfragen-Bearbeitung",
    "products.ai.feature4": "Mehrsprachige Unterstützung",
  },
  fr: {
    // Header
    "nav.home": "Accueil",
    "nav.ecosystem": "Écosystème",
    "nav.projects": "Projets",
    "nav.automation": "Automatisation",
    "nav.contact": "Contact",
    
    // Hero
    "hero.title": "AI Byte Consult Ltd",
    "hero.subtitle": "L'avenir des systèmes d'entreprise intelligents",
    "hero.description": "Une entreprise technologique mondiale spécialisée dans le développement de l'IA et l'automatisation des entreprises. Nous concevons des systèmes intelligents pour les entreprises, l'hôtellerie, la santé, la logistique et la recherche — permettant aux organisations du monde entier d'innover.",
    "hero.cta": "Explorer l'écosystème",
    
    // About
    "about.title": "À propos de l'entreprise",
    "about.p1": "AI Byte Consult Ltd. est une entreprise technologique mondiale spécialisée dans l'intelligence artificielle et l'automatisation. Nous concevons des systèmes intelligents qui optimisent les opérations, améliorent la prise de décision et accélèrent la transformation numérique pour les organisations du monde entier.",
    "about.p2": "Nos solutions basées sur l'IA servent diverses industries — des entreprises B2B et B2C à l'hôtellerie, la santé, la logistique, la géologie et la recherche scientifique. Nous construisons des plateformes évolutives qui aident les entreprises à automatiser les flux de travail, analyser efficacement les données et débloquer de nouvelles opportunités grâce à l'innovation intelligente.",
    
    // Ecosystem
    "ecosystem.title": "Notre écosystème",
    "ecosystem.subtitle": "Une suite complète de solutions basées sur l'IA pour l'économie numérique moderne",
    "ecosystem.nics.title": "Écosystème NICS AI",
    "ecosystem.nics.desc": "L'écosystème NICS AI est une infrastructure unifiée d'intelligence artificielle et de blockchain conçue pour connecter les industries, automatiser les flux de travail et permettre la synchronisation des données inter-plateformes.",
    "ecosystem.horeca.title": "NICS AI HoReCa",
    "ecosystem.horeca.desc": "NICS AI HoReCa est une plateforme d'automatisation IA avancée pour les restaurants, bars et cafés. Elle fournit des solutions en marque blanche avec interaction vocale, analyses intelligentes et automatisation des commandes.",
    "ecosystem.geologist.title": "NICS AI Géologue",
    "ecosystem.geologist.desc": "NICS AI Géologue est une plateforme analytique connectant la géologie, l'exploitation minière et la généalogie par la fusion intelligente des données.",
    "ecosystem.aquaterra.title": "AquaTerra World (Métavers)",
    "ecosystem.aquaterra.desc": "AquaTerra World est un métavers immersif piloté par l'IA qui unit collaboration virtuelle, divertissement et innovation commerciale.",
    "ecosystem.pantheon.title": "Panthéon des Éternels",
    "ecosystem.pantheon.desc": "Pantheon of Eternals AI est une collection révolutionnaire d'entités iNFT interactives inspirées de la mythologie ancienne.",
    "ecosystem.pride.title": "Réseau social PRIDE",
    "ecosystem.pride.desc": "PRIDE Social Network est une plateforme communautaire Web3 décentralisée qui récompense la créativité et l'engagement avec des tokens natifs.",
    
    // Projects
    "projects.title": "Notre travail en action",
    "projects.subtitle": "De vraies solutions offrant des résultats mesurables pour les entreprises avant-gardistes",
    "projects.restaurant.title": "Automatisation de chaîne de restaurants",
    "projects.restaurant.desc": "Commande intelligente et service client IA pour TasteWave Bistro. Efficacité augmentée de 150%.",
    "projects.logistics.title": "IA Parser Logistique",
    "projects.logistics.desc": "Suivi de chaîne d'approvisionnement en temps réel pour CargoNova avec analyses prédictives.",
    "projects.hotel.title": "Automatisation de réservation hôtelière",
    "projects.hotel.desc": "Intégration de chatbot WhatsApp pour OceanView Resorts avec expérience de réservation fluide.",
    "projects.nft.title": "Framework d'intelligence NFT",
    "projects.nft.desc": "Système de création d'artefacts basé sur l'IA pour Eternals by Nixie avec synthèse vocale.",
    "projects.clinic.title": "Assistant vocal pour cliniques",
    "projects.clinic.desc": "Automatisation de rendez-vous pour MediCore Health avec traitement du langage naturel.",
    "projects.retail.title": "Plateforme d'analyse retail",
    "projects.retail.desc": "Prédiction des ventes pilotée par l'IA pour UrbanMarket avec optimisation des stocks.",
    
    // Automation Constructor
    "constructor.title": "Constructeur d'automatisation",
    "constructor.subtitle": "Concevez votre automatisation IA personnalisée en minutes — choisissez votre plateforme, modèle et rôle.",
    "constructor.step1": "Sélectionner la plateforme",
    "constructor.step2": "Choisir le modèle IA",
    "constructor.step3": "Définir votre tâche",
    "constructor.step4": "Sélectionner le type d'automatisation",
    "constructor.step5": "Configuration d'intégration",
    "constructor.step5.desc": "Choisissez comment votre automatisation IA se connecte aux systèmes externes — bases de données, API ou webhooks.",
    "constructor.step6": "Vérifier & Soumettre",
    "constructor.task.placeholder": "Décrivez ce que votre automatisation doit faire...",
    "constructor.contact.title": "Coordonnées",
    "constructor.contact.desc": "Veuillez entrer au moins un moyen de vous contacter :",
    "constructor.skip": "💡 Pas sûr ? Choisissez plus tard",
    "constructor.back": "Retour",
    "constructor.next": "Suivant",
    "constructor.submit": "Soumettre la commande",
    "constructor.success": "✅ Demande envoyée avec succès ! Nous vous contacterons bientôt.",
    "constructor.error.platform": "Veuillez sélectionner une plateforme",
    "constructor.error.model": "Veuillez sélectionner un modèle IA",
    "constructor.error.task": "Veuillez décrire votre tâche",
    "constructor.error.role": "Veuillez sélectionner un type d'automatisation",
    "constructor.error.contact": "Veuillez entrer au moins une méthode de contact.",
    
    // AI Automation Fix
    "aifix.title": "AI Automation Fix",
    "aifix.subtitle": "Automatisation d'entreprise alimentée par l'IA pour les entreprises mondiales",
    "aifix.intro1": "AI ByteConsult Ltd est une entreprise technologique mondiale spécialisée dans l'automatisation d'entreprise alimentée par l'IA, les systèmes intelligents et l'automatisation avancée des flux de travail pour les entreprises des secteurs de l'entreprise, de l'hôtellerie, de la santé et des services.",
    "aifix.intro2": "Notre solution phare, AI Automation Fix, est conçue pour automatiser un processus métier principal rapidement et efficacement, offrant des résultats mesurables en 1 à 3 jours ouvrables.",
    "aifix.included": "Ce qui est inclus",
    "aifix.included.1": "Audit d'automatisation rapide (20-30 minutes)",
    "aifix.included.2": "Automatisation d'un processus métier à fort impact",
    "aifix.included.3": "Flux de travail alimentés par l'IA et intégrations système",
    "aifix.included.4": "Documentation et support continu optionnel",
    "aifix.benefits": "Avantages commerciaux",
    "aifix.benefits.1": "Réduction de la charge de travail manuelle",
    "aifix.benefits.2": "Temps de réponse plus rapides pour les leads et clients",
    "aifix.benefits.3": "Amélioration de l'efficacité opérationnelle",
    "aifix.benefits.4": "Processus évolutifs pilotés par l'IA",
    "aifix.pricing": "Exemples de tarification",
    "aifix.pricing.audit": "Audit d'automatisation",
    "aifix.pricing.impl": "Implémentation",
    "aifix.pricing.support": "Support mensuel",
    "aifix.usecases": "Cas d'utilisation typiques",
    "aifix.usecase.lead": "Gestionnaire de leads IA",
    "aifix.usecase.lead.desc": "Réception, qualification, routage",
    "aifix.usecase.sales": "Assistant commercial IA",
    "aifix.usecase.sales.desc": "Qualification et support des prospects",
    "aifix.usecase.content": "Moteur de contenu IA",
    "aifix.usecase.content.desc": "Flux de travail de contenu automatisés",
    "aifix.usecase.support": "Agent de support IA",
    "aifix.usecase.support.desc": "Assistance client 24/7",
    "aifix.usecase.owner": "Assistant propriétaire IA",
    "aifix.usecase.owner.desc": "Résumés et insights internes",
    "aifix.howitworks": "Comment ça marche",
    "aifix.step1": "Appel de découverte pour comprendre votre flux de travail",
    "aifix.step2": "Identification de l'automatisation à plus fort impact",
    "aifix.step3": "Construction et déploiement avec IA, API et plateformes d'automatisation",
    "aifix.step4": "Livraison, documentation et support optionnel",
    "aifix.cta.title": "Prêt à automatiser votre entreprise avec l'IA ?",
    "aifix.cta.subtitle": "Réservez un audit d'automatisation ou contactez notre équipe pour commencer.",
    "aifix.cta.button": "Commencer maintenant",
    
    // Testimonials
    "testimonials.title": "Approuvé par les innovateurs",
    "testimonials.subtitle": "Découvrez ce que nos clients disent de leur collaboration avec nous",
    "testimonials.1.quote": "AI Byte Consult a révolutionné nos opérations logistiques. Le système de suivi en temps réel nous a fait gagner d'innombrables heures et a amélioré notre précision de livraison de 95%.",
    "testimonials.1.author": "Maria Lopez",
    "testimonials.1.position": "PDG, CargoNova",
    "testimonials.2.quote": "Leur système d'automatisation a doublé l'efficacité de notre restaurant. Nous servons maintenant plus de clients avec une meilleure précision et un personnel plus heureux.",
    "testimonials.2.author": "David Chen",
    "testimonials.2.position": "Fondateur, TasteWave Bistro",
    "testimonials.3.quote": "Notre lancement NFT est devenu vraiment intelligent grâce à leur couche IA. Les avatars vocaux ont créé un niveau d'engagement entièrement nouveau.",
    "testimonials.3.author": "Elena Rossi",
    "testimonials.3.position": "Chef de projet NFT",
    
    // Team
    "team.title": "Rencontrez les fondateurs",
    "team.subtitle": "Les visionnaires derrière AI Byte Consult Ltd.",
    "team.alex.name": "Alexander Lunin",
    "team.alex.role": "Co-fondateur & Architecte IA",
    "team.alex.bio": "Dirige l'architecture IA et les intégrations Web3 à travers l'écosystème Nixie. Plus de 15 ans d'expérience dans la technologie de pointe.",
    "team.aleksandr.name": "Aleksandr Tochilov",
    "team.aleksandr.role": "Co-fondateur & Directeur produit",
    "team.aleksandr.bio": "Se concentre sur les systèmes d'automatisation, les solutions clients et la conception d'écosystèmes créatifs. Passionné par la transformation de technologies complexes en solutions simples.",
    
    // Contact
    "contact.title": "Nous contacter",
    "contact.subtitle": "Construisons ensemble l'avenir de l'automatisation",
    "contact.name": "Nom",
    "contact.name.placeholder": "Votre nom",
    "contact.email": "Email",
    "contact.email.placeholder": "votre.email@exemple.fr",
    "contact.message": "Message",
    "contact.message.placeholder": "Parlez-nous de votre projet...",
    "contact.submit": "Envoyer le message",
    "contact.success": "Message envoyé ! Nous vous répondrons bientôt.",
    
    // Newsletter
    "newsletter.title": "Restez informé",
    "newsletter.subtitle": "Rejoignez nos mises à jour d'innovation et soyez le premier à connaître les nouvelles fonctionnalités et insights",
    "newsletter.placeholder": "votre.email@exemple.fr",
    "newsletter.submit": "S'abonner",
    "newsletter.success": "Merci de vous être abonné à notre newsletter !",
    
    // Footer
    "footer.description": "Automatisation intelligente, solutions Blockchain & Web3 — construire l'avenir de la technologie d'entreprise au sein de l'écosystème NICS AI.",
    "footer.quicklinks": "Liens rapides",
    "footer.home": "Accueil",
    "footer.ecosystem": "Écosystème",
    "footer.projects": "Projets",
    "footer.contact": "Contact",
    "footer.legal": "Légal",
    "footer.privacy": "Politique de confidentialité",
    "footer.terms": "Conditions d'utilisation",
    "footer.copyright": "AI Byte Consult Ltd. Tous droits réservés.",
    
    // Telegram Products
    "products.badge": "Forfaits de démarrage",
    "products.title": "Solutions Telegram",
    "products.subtitle": "Outils Telegram professionnels pour renforcer votre présence commerciale et automatiser les interactions clients",
    "products.oneTime": "unique",
    "products.buyNow": "Acheter maintenant",
    "products.note": "Paiement sécurisé via Revolut. Livraison sous 1-3 jours ouvrables.",
    
    "products.card.title": "Carte Digitale",
    "products.card.subtitle": "Carte de visite Telegram",
    "products.card.description": "Un bot de carte de visite numérique professionnel qui présente vos services, coordonnées et liens sociaux dans une interface Telegram élégante.",
    "products.card.feature1": "Design personnalisé à votre marque",
    "products.card.feature2": "Contact & liens sociaux",
    "products.card.feature3": "Vitrine des services",
    "products.card.feature4": "Partage facile via lien",
    
    "products.bot.title": "Bot Menu",
    "products.bot.subtitle": "Bot de groupe Telegram",
    "products.bot.description": "Un bot intelligent pour votre groupe Telegram avec menu interactif, réponses automatisées et outils de modération pour engager votre communauté.",
    "products.bot.feature1": "Système de menu interactif",
    "products.bot.feature2": "Messages de bienvenue automatiques",
    "products.bot.feature3": "Outils de modération de base",
    "products.bot.feature4": "Commandes personnalisées",
    
    "products.ai.title": "Assistant IA",
    "products.ai.subtitle": "Bot de groupe alimenté par l'IA",
    "products.ai.description": "Un bot IA intelligent pour les groupes avec catalogue de produits, réponses intelligentes et IA conversationnelle pour gérer automatiquement les demandes clients.",
    "products.ai.feature1": "Réponses chat alimentées par l'IA",
    "products.ai.feature2": "Affichage du catalogue produits",
    "products.ai.feature3": "Gestion des demandes de commande",
    "products.ai.feature4": "Support multilingue",
  },
  ar: {
    // Header
    "nav.home": "الرئيسية",
    "nav.ecosystem": "النظام البيئي",
    "nav.projects": "المشاريع",
    "nav.automation": "الأتمتة",
    "nav.contact": "اتصل بنا",
    
    // Hero
    "hero.title": "AI Byte Consult Ltd",
    "hero.subtitle": "مستقبل أنظمة الأعمال الذكية",
    "hero.description": "شركة تكنولوجيا عالمية متخصصة في تطوير الذكاء الاصطناعي وأتمتة الأعمال. نصمم أنظمة ذكية للمؤسسات والضيافة والرعاية الصحية واللوجستيات والبحث — لتمكين المؤسسات في جميع أنحاء العالم من خلال الابتكار.",
    "hero.cta": "استكشف النظام البيئي",
    
    // About
    "about.title": "عن الشركة",
    "about.p1": "AI Byte Consult Ltd. هي شركة تكنولوجيا عالمية متخصصة في الذكاء الاصطناعي والأتمتة. نصمم أنظمة ذكية تحسن العمليات وتعزز صنع القرار وتسرع التحول الرقمي للمؤسسات في جميع أنحاء العالم.",
    "about.p2": "تخدم حلولنا المدعومة بالذكاء الاصطناعي صناعات متنوعة — من مؤسسات B2B وB2C إلى الضيافة والرعاية الصحية واللوجستيات والجيولوجيا والبحث العلمي. نبني منصات قابلة للتطوير تساعد الشركات على أتمتة سير العمل وتحليل البيانات بكفاءة وفتح فرص جديدة من خلال الابتكار الذكي.",
    
    // Ecosystem
    "ecosystem.title": "نظامنا البيئي",
    "ecosystem.subtitle": "مجموعة شاملة من الحلول المدعومة بالذكاء الاصطناعي للاقتصاد الرقمي الحديث",
    "ecosystem.nics.title": "نظام NICS AI البيئي",
    "ecosystem.nics.desc": "نظام NICS AI البيئي هو بنية تحتية موحدة للذكاء الاصطناعي والبلوكتشين مصممة لربط الصناعات وأتمتة سير العمل وتمكين مزامنة البيانات عبر المنصات.",
    "ecosystem.horeca.title": "NICS AI HoReCa",
    "ecosystem.horeca.desc": "NICS AI HoReCa هي منصة أتمتة ذكاء اصطناعي متقدمة للمطاعم والبارات والمقاهي. توفر حلول العلامة البيضاء مع التفاعل الصوتي والتحليلات الذكية وأتمتة الطلبات.",
    "ecosystem.geologist.title": "NICS AI الجيولوجي",
    "ecosystem.geologist.desc": "NICS AI الجيولوجي هي منصة تحليلية تربط الجيولوجيا والتعدين وعلم الأنساب من خلال دمج البيانات الذكي.",
    "ecosystem.aquaterra.title": "عالم AquaTerra (ميتافيرس)",
    "ecosystem.aquaterra.desc": "عالم AquaTerra هو ميتافيرس غامر مدفوع بالذكاء الاصطناعي يوحد التعاون الافتراضي والترفيه والابتكار التجاري.",
    "ecosystem.pantheon.title": "بانثيون الخالدين",
    "ecosystem.pantheon.desc": "Pantheon of Eternals AI هي مجموعة ثورية من كيانات iNFT التفاعلية المستوحاة من الأساطير القديمة.",
    "ecosystem.pride.title": "شبكة PRIDE الاجتماعية",
    "ecosystem.pride.desc": "شبكة PRIDE الاجتماعية هي منصة مجتمع Web3 لامركزية تكافئ الإبداع والمشاركة برموز أصلية.",
    
    // Projects
    "projects.title": "عملنا في العمل",
    "projects.subtitle": "حلول حقيقية تقدم نتائج قابلة للقياس للشركات ذات التفكير المستقبلي",
    "projects.restaurant.title": "أتمتة سلسلة المطاعم",
    "projects.restaurant.desc": "طلب ذكي وخدمة عملاء بالذكاء الاصطناعي لـ TasteWave Bistro. زيادة الكفاءة بنسبة 150%.",
    "projects.logistics.title": "الذكاء الاصطناعي لتحليل اللوجستيات",
    "projects.logistics.desc": "تتبع سلسلة التوريد في الوقت الفعلي لـ CargoNova مع التحليلات التنبؤية.",
    "projects.hotel.title": "أتمتة حجز الفنادق",
    "projects.hotel.desc": "تكامل روبوت دردشة واتساب لـ OceanView Resorts مع تجربة حجز سلسة.",
    "projects.nft.title": "إطار ذكاء NFT",
    "projects.nft.desc": "نظام إنشاء قطع أثرية قائم على الذكاء الاصطناعي لـ Eternals by Nixie مع تركيب الصوت.",
    "projects.clinic.title": "مساعد صوتي للعيادات",
    "projects.clinic.desc": "أتمتة المواعيد لـ MediCore Health مع معالجة اللغة الطبيعية.",
    "projects.retail.title": "منصة تحليلات التجزئة",
    "projects.retail.desc": "توقع مبيعات مدفوع بالذكاء الاصطناعي لـ UrbanMarket مع تحسين المخزون.",
    
    // Automation Constructor
    "constructor.title": "منشئ الأتمتة",
    "constructor.subtitle": "صمم أتمتة الذكاء الاصطناعي المخصصة في دقائق — اختر منصتك ونموذجك ودورك.",
    "constructor.step1": "اختر المنصة",
    "constructor.step2": "اختر نموذج الذكاء الاصطناعي",
    "constructor.step3": "حدد مهمتك",
    "constructor.step4": "اختر نوع الأتمتة",
    "constructor.step5": "إعداد التكامل",
    "constructor.step5.desc": "اختر كيف تتصل أتمتة الذكاء الاصطناعي الخاصة بك بالأنظمة الخارجية — قواعد البيانات أو واجهات برمجة التطبيقات أو الويب هوك.",
    "constructor.step6": "مراجعة وإرسال",
    "constructor.task.placeholder": "صف ما يجب أن تفعله أتمتتك...",
    "constructor.contact.title": "معلومات الاتصال",
    "constructor.contact.desc": "يرجى إدخال طريقة واحدة على الأقل للوصول إليك:",
    "constructor.skip": "💡 غير متأكد؟ اختر لاحقاً",
    "constructor.back": "رجوع",
    "constructor.next": "التالي",
    "constructor.submit": "إرسال الطلب",
    "constructor.success": "✅ تم إرسال الطلب بنجاح! سنتصل بك قريباً.",
    "constructor.error.platform": "يرجى اختيار منصة",
    "constructor.error.model": "يرجى اختيار نموذج ذكاء اصطناعي",
    "constructor.error.task": "يرجى وصف مهمتك",
    "constructor.error.role": "يرجى اختيار نوع الأتمتة",
    "constructor.error.contact": "يرجى إدخال طريقة اتصال واحدة على الأقل.",
    
    // AI Automation Fix
    "aifix.title": "AI Automation Fix",
    "aifix.subtitle": "أتمتة الأعمال المدعومة بالذكاء الاصطناعي للشركات العالمية",
    "aifix.intro1": "AI ByteConsult Ltd هي شركة تكنولوجيا عالمية متخصصة في أتمتة الأعمال المدعومة بالذكاء الاصطناعي والأنظمة الذكية وأتمتة سير العمل المتقدمة للشركات عبر قطاعات المؤسسات والضيافة والرعاية الصحية والخدمات.",
    "aifix.intro2": "حلنا الرائد، AI Automation Fix، مصمم لأتمتة عملية تجارية أساسية واحدة بسرعة وكفاءة، مع تقديم نتائج قابلة للقياس في غضون 1-3 أيام عمل.",
    "aifix.included": "ما هو متضمن",
    "aifix.included.1": "تدقيق أتمتة سريع (20-30 دقيقة)",
    "aifix.included.2": "أتمتة عملية تجارية عالية التأثير",
    "aifix.included.3": "سير عمل مدعوم بالذكاء الاصطناعي وتكاملات النظام",
    "aifix.included.4": "التوثيق والدعم المستمر الاختياري",
    "aifix.benefits": "الفوائد التجارية",
    "aifix.benefits.1": "تقليل عبء العمل اليدوي",
    "aifix.benefits.2": "أوقات استجابة أسرع للعملاء المحتملين والعملاء",
    "aifix.benefits.3": "تحسين الكفاءة التشغيلية",
    "aifix.benefits.4": "عمليات قابلة للتطوير مدفوعة بالذكاء الاصطناعي",
    "aifix.pricing": "أمثلة على الأسعار",
    "aifix.pricing.audit": "تدقيق الأتمتة",
    "aifix.pricing.impl": "التنفيذ",
    "aifix.pricing.support": "الدعم الشهري",
    "aifix.usecases": "حالات الاستخدام النموذجية",
    "aifix.usecase.lead": "معالج العملاء المحتملين بالذكاء الاصطناعي",
    "aifix.usecase.lead.desc": "الاستقبال والتأهيل والتوجيه",
    "aifix.usecase.sales": "مساعد المبيعات بالذكاء الاصطناعي",
    "aifix.usecase.sales.desc": "تأهيل ودعم العملاء المحتملين",
    "aifix.usecase.content": "محرك المحتوى بالذكاء الاصطناعي",
    "aifix.usecase.content.desc": "سير عمل المحتوى الآلي",
    "aifix.usecase.support": "وكيل الدعم بالذكاء الاصطناعي",
    "aifix.usecase.support.desc": "مساعدة العملاء على مدار الساعة",
    "aifix.usecase.owner": "مساعد المالك بالذكاء الاصطناعي",
    "aifix.usecase.owner.desc": "ملخصات ورؤى داخلية",
    "aifix.howitworks": "كيف يعمل",
    "aifix.step1": "مكالمة اكتشاف لفهم سير عملك",
    "aifix.step2": "تحديد الأتمتة ذات التأثير الأعلى",
    "aifix.step3": "البناء والنشر باستخدام الذكاء الاصطناعي وواجهات برمجة التطبيقات ومنصات الأتمتة",
    "aifix.step4": "التسليم والتوثيق والدعم الاختياري",
    "aifix.cta.title": "هل أنت مستعد لأتمتة عملك بالذكاء الاصطناعي؟",
    "aifix.cta.subtitle": "احجز تدقيق أتمتة أو اتصل بفريقنا للبدء.",
    "aifix.cta.button": "ابدأ الآن",
    
    // Testimonials
    "testimonials.title": "موثوق به من قبل المبتكرين",
    "testimonials.subtitle": "اطلع على ما يقوله عملاؤنا عن العمل معنا",
    "testimonials.1.quote": "أحدثت AI Byte Consult ثورة في عملياتنا اللوجستية. وفر لنا نظام التتبع في الوقت الفعلي ساعات لا حصر لها وحسّن دقة التسليم لدينا بنسبة 95%.",
    "testimonials.1.author": "ماريا لوبيز",
    "testimonials.1.position": "الرئيس التنفيذي، CargoNova",
    "testimonials.2.quote": "ضاعف نظام الأتمتة الخاص بهم كفاءة مطعمنا. نحن الآن نخدم المزيد من العملاء بدقة أفضل وموظفين أسعد.",
    "testimonials.2.author": "ديفيد تشين",
    "testimonials.2.position": "مؤسس، TasteWave Bistro",
    "testimonials.3.quote": "أصبح إطلاق NFT الخاص بنا ذكياً حقاً بفضل طبقة الذكاء الاصطناعي الخاصة بهم. خلقت الأفاتار المفعّلة بالصوت مستوى جديداً تماماً من المشاركة.",
    "testimonials.3.author": "إيلينا روسي",
    "testimonials.3.position": "قائدة مشروع NFT",
    
    // Team
    "team.title": "تعرف على المؤسسين",
    "team.subtitle": "أصحاب الرؤية وراء AI Byte Consult Ltd.",
    "team.alex.name": "ألكسندر لونين",
    "team.alex.role": "مؤسس مشارك ومهندس ذكاء اصطناعي",
    "team.alex.bio": "يقود هندسة الذكاء الاصطناعي وتكاملات Web3 عبر نظام Nixie البيئي. أكثر من 15 عاماً من الخبرة في التكنولوجيا المتطورة.",
    "team.aleksandr.name": "ألكسندر توتشيلوف",
    "team.aleksandr.role": "مؤسس مشارك ومدير المنتج",
    "team.aleksandr.bio": "يركز على أنظمة الأتمتة وحلول العملاء وتصميم النظام البيئي الإبداعي. شغوف بتحويل التكنولوجيا المعقدة إلى حلول بسيطة.",
    
    // Contact
    "contact.title": "تواصل معنا",
    "contact.subtitle": "لنبني معاً مستقبل الأتمتة",
    "contact.name": "الاسم",
    "contact.name.placeholder": "اسمك",
    "contact.email": "البريد الإلكتروني",
    "contact.email.placeholder": "بريدك@مثال.com",
    "contact.message": "الرسالة",
    "contact.message.placeholder": "أخبرنا عن مشروعك...",
    "contact.submit": "إرسال الرسالة",
    "contact.success": "تم إرسال الرسالة! سنرد عليك قريباً.",
    
    // Newsletter
    "newsletter.title": "ابق على اطلاع",
    "newsletter.subtitle": "انضم إلى تحديثات الابتكار لدينا وكن أول من يعرف عن الميزات والرؤى الجديدة",
    "newsletter.placeholder": "بريدك@مثال.com",
    "newsletter.submit": "اشترك",
    "newsletter.success": "شكراً لاشتراكك في نشرتنا الإخبارية!",
    
    // Footer
    "footer.description": "أتمتة ذكية وحلول البلوكتشين و Web3 — نبني مستقبل تكنولوجيا الأعمال ضمن نظام NICS AI البيئي.",
    "footer.quicklinks": "روابط سريعة",
    "footer.home": "الرئيسية",
    "footer.ecosystem": "النظام البيئي",
    "footer.projects": "المشاريع",
    "footer.contact": "اتصل بنا",
    "footer.legal": "قانوني",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
    "footer.copyright": "AI Byte Consult Ltd. جميع الحقوق محفوظة.",
    
    // Telegram Products
    "products.badge": "باقات البداية",
    "products.title": "حلول تيليجرام",
    "products.subtitle": "أدوات تيليجرام احترافية لتعزيز تواجدك التجاري وأتمتة تفاعلات العملاء",
    "products.oneTime": "مرة واحدة",
    "products.buyNow": "اشترِ الآن",
    "products.note": "دفع آمن عبر Revolut. التسليم خلال 1-3 أيام عمل.",
    
    "products.card.title": "البطاقة الرقمية",
    "products.card.subtitle": "بطاقة أعمال تيليجرام",
    "products.card.description": "بوت بطاقة أعمال رقمية احترافية يعرض خدماتك ومعلومات الاتصال وروابط التواصل الاجتماعي في واجهة تيليجرام أنيقة.",
    "products.card.feature1": "تصميم مخصص بعلامتك التجارية",
    "products.card.feature2": "روابط الاتصال والتواصل الاجتماعي",
    "products.card.feature3": "عرض الخدمات",
    "products.card.feature4": "مشاركة سهلة عبر الرابط",
    
    "products.bot.title": "بوت القائمة",
    "products.bot.subtitle": "بوت مجموعة تيليجرام",
    "products.bot.description": "بوت ذكي لمجموعة تيليجرام الخاصة بك مع قائمة تفاعلية وردود آلية وأدوات إشراف لإشراك مجتمعك.",
    "products.bot.feature1": "نظام قائمة تفاعلي",
    "products.bot.feature2": "رسائل ترحيب آلية",
    "products.bot.feature3": "أدوات إشراف أساسية",
    "products.bot.feature4": "أوامر مخصصة",
    
    "products.ai.title": "مساعد الذكاء الاصطناعي",
    "products.ai.subtitle": "بوت مجموعة مدعوم بالذكاء الاصطناعي",
    "products.ai.description": "بوت ذكاء اصطناعي ذكي للمجموعات مع كتالوج المنتجات والردود الذكية والذكاء الاصطناعي المحادثي للتعامل مع استفسارات العملاء تلقائياً.",
    "products.ai.feature1": "ردود محادثة مدعومة بالذكاء الاصطناعي",
    "products.ai.feature2": "عرض كتالوج المنتجات",
    "products.ai.feature3": "معالجة استفسارات الطلبات",
    "products.ai.feature4": "دعم متعدد اللغات",
  },
  zh: {
    // Header
    "nav.home": "首页",
    "nav.ecosystem": "生态系统",
    "nav.projects": "项目",
    "nav.automation": "自动化",
    "nav.contact": "联系我们",
    
    // Hero
    "hero.title": "AI Byte Consult Ltd",
    "hero.subtitle": "智能商业系统的未来",
    "hero.description": "一家专注于人工智能开发和业务自动化的全球科技公司。我们为企业、酒店、医疗、物流和研究领域设计智能系统——通过创新赋能全球组织。",
    "hero.cta": "探索生态系统",
    
    // About
    "about.title": "关于公司",
    "about.p1": "AI Byte Consult Ltd. 是一家专注于人工智能和自动化的全球科技公司。我们设计智能系统，优化运营、增强决策制定，并加速全球组织的数字化转型。",
    "about.p2": "我们的AI驱动解决方案服务于多个行业——从B2B和B2C企业到酒店、医疗、物流、地质和科学研究。我们构建可扩展的平台，帮助企业自动化工作流程、高效分析数据，并通过智能创新开启新机遇。",
    
    // Ecosystem
    "ecosystem.title": "我们的生态系统",
    "ecosystem.subtitle": "为现代数字经济提供全面的AI驱动解决方案套件",
    "ecosystem.nics.title": "NICS AI 生态系统",
    "ecosystem.nics.desc": "NICS AI生态系统是一个统一的人工智能和区块链基础设施，旨在连接各行业、自动化工作流程并实现跨平台数据同步。",
    "ecosystem.horeca.title": "NICS AI 餐饮",
    "ecosystem.horeca.desc": "NICS AI HoReCa是一个先进的AI自动化平台，适用于餐厅、酒吧和咖啡馆。它提供白标解决方案，具有语音交互、智能分析和订单自动化功能。",
    "ecosystem.geologist.title": "NICS AI 地质学家",
    "ecosystem.geologist.desc": "NICS AI地质学家是一个分析平台，通过智能数据融合连接地质、采矿和家谱学。",
    "ecosystem.aquaterra.title": "AquaTerra世界（元宇宙）",
    "ecosystem.aquaterra.desc": "AquaTerra世界是一个沉浸式AI驱动的元宇宙，将虚拟协作、娱乐和商业创新融为一体。",
    "ecosystem.pantheon.title": "永恒万神殿",
    "ecosystem.pantheon.desc": "永恒万神殿AI是一个革命性的交互式iNFT实体集合，灵感来自古代神话。",
    "ecosystem.pride.title": "PRIDE社交网络",
    "ecosystem.pride.desc": "PRIDE社交网络是一个去中心化的Web3社区平台，用原生代币奖励创造力和参与度。",
    
    // Projects
    "projects.title": "我们的工作成果",
    "projects.subtitle": "为具有前瞻性思维的企业提供可衡量结果的真实解决方案",
    "projects.restaurant.title": "餐厅连锁自动化",
    "projects.restaurant.desc": "为TasteWave Bistro提供智能点餐和AI客户服务。效率提升150%。",
    "projects.logistics.title": "物流解析AI",
    "projects.logistics.desc": "为CargoNova提供实时供应链跟踪和预测分析。",
    "projects.hotel.title": "酒店预订自动化",
    "projects.hotel.desc": "为OceanView Resorts集成WhatsApp聊天机器人，提供无缝预订体验。",
    "projects.nft.title": "NFT智能框架",
    "projects.nft.desc": "为Eternals by Nixie提供基于AI的文物创建系统，具有语音合成功能。",
    "projects.clinic.title": "诊所语音助手",
    "projects.clinic.desc": "为MediCore Health提供自然语言处理的预约自动化。",
    "projects.retail.title": "零售分析平台",
    "projects.retail.desc": "为UrbanMarket提供AI驱动的销售预测和库存优化。",
    
    // Automation Constructor
    "constructor.title": "自动化构建器",
    "constructor.subtitle": "几分钟内设计您的自定义AI自动化——选择您的平台、模型和角色。",
    "constructor.step1": "选择平台",
    "constructor.step2": "选择AI模型",
    "constructor.step3": "定义您的任务",
    "constructor.step4": "选择自动化类型",
    "constructor.step5": "集成设置",
    "constructor.step5.desc": "选择您的AI自动化如何连接外部系统——数据库、API或Webhook。",
    "constructor.step6": "审核并提交",
    "constructor.task.placeholder": "描述您的自动化应该做什么...",
    "constructor.contact.title": "联系信息",
    "constructor.contact.desc": "请至少提供一种联系方式：",
    "constructor.skip": "💡 不确定？稍后选择",
    "constructor.back": "返回",
    "constructor.next": "下一步",
    "constructor.submit": "提交订单",
    "constructor.success": "✅ 请求发送成功！我们将很快联系您。",
    "constructor.error.platform": "请选择一个平台",
    "constructor.error.model": "请选择一个AI模型",
    "constructor.error.task": "请描述您的任务",
    "constructor.error.role": "请选择自动化类型",
    "constructor.error.contact": "请至少输入一种联系方式。",
    
    // AI Automation Fix
    "aifix.title": "AI自动化修复",
    "aifix.subtitle": "为全球企业提供AI驱动的业务自动化",
    "aifix.intro1": "AI ByteConsult Ltd是一家全球科技公司，专注于AI驱动的业务自动化、智能系统和先进的工作流自动化，服务于企业、酒店、医疗和服务行业。",
    "aifix.intro2": "我们的旗舰解决方案AI Automation Fix旨在快速高效地自动化一个核心业务流程，在1-3个工作日内交付可衡量的结果。",
    "aifix.included": "包含内容",
    "aifix.included.1": "快速自动化审计（20-30分钟）",
    "aifix.included.2": "一个高影响力业务流程的自动化",
    "aifix.included.3": "AI驱动的工作流和系统集成",
    "aifix.included.4": "文档和可选的持续支持",
    "aifix.benefits": "商业利益",
    "aifix.benefits.1": "减少手动工作量",
    "aifix.benefits.2": "更快的潜在客户和客户响应时间",
    "aifix.benefits.3": "提高运营效率",
    "aifix.benefits.4": "可扩展的AI驱动流程",
    "aifix.pricing": "定价示例",
    "aifix.pricing.audit": "自动化审计",
    "aifix.pricing.impl": "实施",
    "aifix.pricing.support": "月度支持",
    "aifix.usecases": "典型自动化用例",
    "aifix.usecase.lead": "AI潜在客户处理器",
    "aifix.usecase.lead.desc": "接收、资格审查、路由",
    "aifix.usecase.sales": "AI销售助手",
    "aifix.usecase.sales.desc": "潜在客户资格审查和支持",
    "aifix.usecase.content": "AI内容引擎",
    "aifix.usecase.content.desc": "自动化内容工作流",
    "aifix.usecase.support": "AI支持代理",
    "aifix.usecase.support.desc": "24/7客户服务",
    "aifix.usecase.owner": "AI业主助手",
    "aifix.usecase.owner.desc": "内部摘要和洞察",
    "aifix.howitworks": "工作原理",
    "aifix.step1": "发现电话以了解您的工作流程",
    "aifix.step2": "识别最高影响力的自动化",
    "aifix.step3": "使用AI、API和自动化平台构建和部署",
    "aifix.step4": "交付、文档和可选支持",
    "aifix.cta.title": "准备好用AI自动化您的业务了吗？",
    "aifix.cta.subtitle": "预约自动化审计或联系我们的团队开始。",
    "aifix.cta.button": "立即开始",
    
    // Testimonials
    "testimonials.title": "受创新者信赖",
    "testimonials.subtitle": "看看我们的客户对与我们合作的评价",
    "testimonials.1.quote": "AI Byte Consult彻底改变了我们的物流运营。实时跟踪系统为我们节省了无数小时，并将我们的交付准确率提高了95%。",
    "testimonials.1.author": "玛丽亚·洛佩兹",
    "testimonials.1.position": "CEO，CargoNova",
    "testimonials.2.quote": "他们的自动化系统使我们餐厅的效率翻了一番。我们现在以更高的准确度服务更多客户，员工也更开心。",
    "testimonials.2.author": "大卫·陈",
    "testimonials.2.position": "创始人，TasteWave Bistro",
    "testimonials.3.quote": "多亏了他们的AI层，我们的NFT发布变得真正智能。语音启用的头像创造了全新的参与水平。",
    "testimonials.3.author": "埃琳娜·罗西",
    "testimonials.3.position": "NFT项目负责人",
    
    // Team
    "team.title": "认识创始人",
    "team.subtitle": "AI Byte Consult Ltd背后的远见者",
    "team.alex.name": "亚历山大·卢宁",
    "team.alex.role": "联合创始人兼AI架构师",
    "team.alex.bio": "领导整个Nixie生态系统的AI架构和Web3集成。拥有超过15年的前沿技术经验。",
    "team.aleksandr.name": "亚历山大·托奇洛夫",
    "team.aleksandr.role": "联合创始人兼产品总监",
    "team.aleksandr.bio": "专注于自动化系统、客户解决方案和创意生态系统设计。热衷于将复杂技术转化为简单解决方案。",
    
    // Contact
    "contact.title": "联系我们",
    "contact.subtitle": "让我们共同构建自动化的未来",
    "contact.name": "姓名",
    "contact.name.placeholder": "您的姓名",
    "contact.email": "电子邮件",
    "contact.email.placeholder": "your.email@example.com",
    "contact.message": "留言",
    "contact.message.placeholder": "告诉我们您的项目...",
    "contact.submit": "发送消息",
    "contact.success": "消息已发送！我们会尽快回复您。",
    
    // Newsletter
    "newsletter.title": "保持更新",
    "newsletter.subtitle": "加入我们的创新更新，第一时间了解新功能和洞察",
    "newsletter.placeholder": "your.email@example.com",
    "newsletter.submit": "订阅",
    "newsletter.success": "感谢您订阅我们的通讯！",
    
    // Footer
    "footer.description": "智能自动化、区块链和Web3解决方案——在NICS AI生态系统中构建商业技术的未来。",
    "footer.quicklinks": "快速链接",
    "footer.home": "首页",
    "footer.ecosystem": "生态系统",
    "footer.projects": "项目",
    "footer.contact": "联系我们",
    "footer.legal": "法律",
    "footer.privacy": "隐私政策",
    "footer.terms": "服务条款",
    "footer.copyright": "AI Byte Consult Ltd. 保留所有权利。",
    
    // Telegram Products
    "products.badge": "入门套餐",
    "products.title": "Telegram解决方案",
    "products.subtitle": "专业的Telegram工具，提升您的商业形象并自动化客户互动",
    "products.oneTime": "一次性",
    "products.buyNow": "立即购买",
    "products.note": "通过Revolut安全支付。1-3个工作日内交付。",
    
    "products.card.title": "数字名片",
    "products.card.subtitle": "Telegram商务名片",
    "products.card.description": "一个专业的数字商务名片机器人，在优雅的Telegram界面中展示您的服务、联系信息和社交链接。",
    "products.card.feature1": "自定义品牌设计",
    "products.card.feature2": "联系方式和社交链接",
    "products.card.feature3": "服务展示",
    "products.card.feature4": "通过链接轻松分享",
    
    "products.bot.title": "菜单机器人",
    "products.bot.subtitle": "Telegram群组机器人",
    "products.bot.description": "一个智能的Telegram群组机器人，具有交互式菜单、自动回复和管理工具，用于吸引您的社区。",
    "products.bot.feature1": "交互式菜单系统",
    "products.bot.feature2": "自动欢迎消息",
    "products.bot.feature3": "基本管理工具",
    "products.bot.feature4": "自定义命令",
    
    "products.ai.title": "AI助手",
    "products.ai.subtitle": "AI驱动的群组机器人",
    "products.ai.description": "一个智能AI群组机器人，具有产品目录、智能回复和对话式AI，自动处理客户咨询。",
    "products.ai.feature1": "AI驱动的聊天回复",
    "products.ai.feature2": "产品目录展示",
    "products.ai.feature3": "订单咨询处理",
    "products.ai.feature4": "多语言支持",
  },
  pl: {
    // Header
    "nav.home": "Strona główna",
    "nav.ecosystem": "Ekosystem",
    "nav.projects": "Projekty",
    "nav.automation": "Automatyzacja",
    "nav.contact": "Kontakt",
    
    // Hero
    "hero.title": "AI Byte Consult Ltd",
    "hero.subtitle": "Przyszłość inteligentnych systemów biznesowych",
    "hero.description": "Globalna firma technologiczna specjalizująca się w rozwoju AI i automatyzacji biznesu. Projektujemy inteligentne systemy dla przedsiębiorstw, hotelarstwa, opieki zdrowotnej, logistyki i badań — wspierając organizacje na całym świecie poprzez innowacje.",
    "hero.cta": "Poznaj ekosystem",
    
    // About
    "about.title": "O firmie",
    "about.p1": "AI Byte Consult Ltd. to globalna firma technologiczna specjalizująca się w sztucznej inteligencji i automatyzacji. Projektujemy inteligentne systemy, które optymalizują operacje, usprawniają podejmowanie decyzji i przyspieszają cyfrową transformację organizacji na całym świecie.",
    "about.p2": "Nasze rozwiązania oparte na AI obsługują różne branże — od przedsiębiorstw B2B i B2C po hotelarstwo, opiekę zdrowotną, logistykę, geologię i badania naukowe.",
    
    // Ecosystem
    "ecosystem.title": "Nasz ekosystem",
    "ecosystem.subtitle": "Kompleksowy zestaw rozwiązań opartych na AI dla nowoczesnej gospodarki cyfrowej",
    "ecosystem.nics.title": "Ekosystem NICS AI",
    "ecosystem.nics.desc": "Ekosystem NICS AI to ujednolicona infrastruktura sztucznej inteligencji i blockchain, zaprojektowana do łączenia branż, automatyzacji przepływów pracy i synchronizacji danych między platformami.",
    "ecosystem.horeca.title": "NICS AI HoReCa",
    "ecosystem.horeca.desc": "NICS AI HoReCa to zaawansowana platforma automatyzacji AI dla restauracji, barów i kawiarni.",
    "ecosystem.geologist.title": "NICS AI Geolog",
    "ecosystem.geologist.desc": "NICS AI Geolog to platforma analityczna łącząca geologię, górnictwo i genealogię poprzez inteligentną fuzję danych.",
    "ecosystem.aquaterra.title": "AquaTerra World (Metaverse)",
    "ecosystem.aquaterra.desc": "AquaTerra World to immersyjny metaverse napędzany przez AI, łączący wirtualną współpracę, rozrywkę i innowacje biznesowe.",
    "ecosystem.pantheon.title": "Panteon Wiecznych",
    "ecosystem.pantheon.desc": "Panteon Wiecznych AI to rewolucyjna kolekcja interaktywnych jednostek iNFT inspirowanych starożytną mitologią.",
    "ecosystem.pride.title": "Sieć społecznościowa PRIDE",
    "ecosystem.pride.desc": "PRIDE Social Network to zdecentralizowana platforma społecznościowa Web3, która nagradza kreatywność i zaangażowanie natywnymi tokenami.",
    
    // Projects
    "projects.title": "Nasze realizacje",
    "projects.subtitle": "Prawdziwe rozwiązania dostarczające mierzalne rezultaty dla przedsiębiorstw zorientowanych na przyszłość",
    "projects.restaurant.title": "Automatyzacja sieci restauracji",
    "projects.restaurant.desc": "Inteligentne zamawianie i obsługa klienta AI dla TasteWave Bistro. Wzrost efektywności o 150%.",
    "projects.logistics.title": "AI Parser logistyczny",
    "projects.logistics.desc": "Śledzenie łańcucha dostaw w czasie rzeczywistym dla CargoNova z analizą predykcyjną.",
    "projects.hotel.title": "Automatyzacja rezerwacji hotelowych",
    "projects.hotel.desc": "Integracja chatbota WhatsApp dla OceanView Resorts z płynnym doświadczeniem rezerwacji.",
    "projects.nft.title": "Framework inteligencji NFT",
    "projects.nft.desc": "System tworzenia artefaktów oparty na AI dla Eternals by Nixie z syntezą głosu.",
    "projects.clinic.title": "Asystent głosowy dla klinik",
    "projects.clinic.desc": "Automatyzacja umawiania wizyt dla MediCore Health z przetwarzaniem języka naturalnego.",
    "projects.retail.title": "Platforma analityki detalicznej",
    "projects.retail.desc": "Prognozowanie sprzedaży oparte na AI dla UrbanMarket z optymalizacją zapasów.",
    
    // Automation Constructor
    "constructor.title": "Konstruktor automatyzacji",
    "constructor.subtitle": "Zaprojektuj swoją niestandardową automatyzację AI w kilka minut — wybierz platformę, model i rolę.",
    "constructor.step1": "Wybierz platformę",
    "constructor.step2": "Wybierz model AI",
    "constructor.step3": "Zdefiniuj swoje zadanie",
    "constructor.step4": "Wybierz typ automatyzacji",
    "constructor.step5": "Konfiguracja integracji",
    "constructor.step5.desc": "Wybierz, jak Twoja automatyzacja AI łączy się z zewnętrznymi systemami.",
    "constructor.step6": "Przegląd i przesłanie",
    "constructor.task.placeholder": "Opisz, co powinna robić Twoja automatyzacja...",
    "constructor.contact.title": "Dane kontaktowe",
    "constructor.contact.desc": "Podaj przynajmniej jeden sposób kontaktu:",
    "constructor.skip": "💡 Nie wiesz? Wybierz później",
    "constructor.back": "Wstecz",
    "constructor.next": "Dalej",
    "constructor.submit": "Wyślij zamówienie",
    "constructor.success": "✅ Żądanie wysłane pomyślnie! Skontaktujemy się wkrótce.",
    "constructor.error.platform": "Wybierz platformę",
    "constructor.error.model": "Wybierz model AI",
    "constructor.error.task": "Opisz swoje zadanie",
    "constructor.error.role": "Wybierz typ automatyzacji",
    "constructor.error.contact": "Podaj przynajmniej jedną metodę kontaktu.",
    
    // AI Automation Fix
    "aifix.title": "AI Automation Fix",
    "aifix.subtitle": "Automatyzacja biznesu oparta na AI dla globalnych firm",
    "aifix.intro1": "AI ByteConsult Ltd to globalna firma technologiczna specjalizująca się w automatyzacji biznesu opartej na AI.",
    "aifix.intro2": "Nasze flagowe rozwiązanie, AI Automation Fix, zostało zaprojektowane do szybkiej i wydajnej automatyzacji jednego podstawowego procesu biznesowego.",
    "aifix.included": "Co zawiera",
    "aifix.included.1": "Szybki audyt automatyzacji (20-30 minut)",
    "aifix.included.2": "Automatyzacja jednego procesu o wysokim wpływie",
    "aifix.included.3": "Przepływy pracy oparte na AI i integracje systemów",
    "aifix.included.4": "Dokumentacja i opcjonalne wsparcie",
    "aifix.benefits": "Korzyści biznesowe",
    "aifix.benefits.1": "Zmniejszone obciążenie ręczną pracą",
    "aifix.benefits.2": "Szybszy czas reakcji na leady i klientów",
    "aifix.benefits.3": "Poprawiona efektywność operacyjna",
    "aifix.benefits.4": "Skalowalne procesy oparte na AI",
    "aifix.pricing": "Przykładowe ceny",
    "aifix.pricing.audit": "Audyt automatyzacji",
    "aifix.pricing.impl": "Wdrożenie",
    "aifix.pricing.support": "Wsparcie miesięczne",
    "aifix.usecases": "Typowe przypadki użycia automatyzacji",
    "aifix.usecase.lead": "AI Lead Handler",
    "aifix.usecase.lead.desc": "Przyjmowanie, kwalifikacja, routing",
    "aifix.usecase.sales": "AI Asystent sprzedaży",
    "aifix.usecase.sales.desc": "Kwalifikacja i wsparcie prospektów",
    "aifix.usecase.content": "AI Silnik treści",
    "aifix.usecase.content.desc": "Automatyzowane przepływy treści",
    "aifix.usecase.support": "AI Agent wsparcia",
    "aifix.usecase.support.desc": "Obsługa klienta 24/7",
    "aifix.usecase.owner": "AI Asystent właściciela",
    "aifix.usecase.owner.desc": "Wewnętrzne podsumowania i wglądy",
    "aifix.howitworks": "Jak to działa",
    "aifix.step1": "Rozmowa odkrywcza, aby zrozumieć Twój przepływ pracy",
    "aifix.step2": "Identyfikacja automatyzacji o najwyższym wpływie",
    "aifix.step3": "Budowanie i wdrażanie przy użyciu AI, API i platform automatyzacji",
    "aifix.step4": "Dostawa, dokumentacja i opcjonalne wsparcie",
    "aifix.cta.title": "Gotowy do automatyzacji swojego biznesu z AI?",
    "aifix.cta.subtitle": "Zarezerwuj audyt automatyzacji lub skontaktuj się z naszym zespołem.",
    "aifix.cta.button": "Rozpocznij teraz",
    
    // Testimonials
    "testimonials.title": "Zaufani przez innowatorów",
    "testimonials.subtitle": "Zobacz, co mówią nasi klienci o współpracy z nami",
    "testimonials.1.quote": "AI Byte Consult zrewolucjonizował nasze operacje logistyczne. System śledzenia w czasie rzeczywistym zaoszczędził nam niezliczone godziny.",
    "testimonials.1.author": "Maria Lopez",
    "testimonials.1.position": "CEO, CargoNova",
    "testimonials.2.quote": "Ich system automatyzacji podwoił efektywność naszej restauracji.",
    "testimonials.2.author": "David Chen",
    "testimonials.2.position": "Założyciel, TasteWave Bistro",
    "testimonials.3.quote": "Nasze uruchomienie NFT stało się naprawdę inteligentne dzięki ich warstwie AI.",
    "testimonials.3.author": "Elena Rossi",
    "testimonials.3.position": "Kierownik projektu NFT",
    
    // Team
    "team.title": "Poznaj założycieli",
    "team.subtitle": "Wizjonerzy stojący za AI Byte Consult Ltd.",
    "team.alex.name": "Alexander Lunin",
    "team.alex.role": "Współzałożyciel i architekt AI",
    "team.alex.bio": "Kieruje architekturą AI i integracjami Web3 w całym ekosystemie Nixie.",
    "team.aleksandr.name": "Aleksandr Tochilov",
    "team.aleksandr.role": "Współzałożyciel i dyrektor produktu",
    "team.aleksandr.bio": "Koncentruje się na systemach automatyzacji, rozwiązaniach dla klientów i projektowaniu kreatywnego ekosystemu.",
    
    // Contact
    "contact.title": "Skontaktuj się",
    "contact.subtitle": "Zbudujmy razem przyszłość automatyzacji",
    "contact.name": "Imię",
    "contact.name.placeholder": "Twoje imię",
    "contact.email": "Email",
    "contact.email.placeholder": "twoj.email@example.com",
    "contact.message": "Wiadomość",
    "contact.message.placeholder": "Opowiedz nam o swoim projekcie...",
    "contact.submit": "Wyślij wiadomość",
    "contact.success": "Wiadomość wysłana! Odezwiemy się wkrótce.",
    
    // Newsletter
    "newsletter.title": "Bądź na bieżąco",
    "newsletter.subtitle": "Dołącz do naszych aktualizacji innowacji",
    "newsletter.placeholder": "twoj.email@example.com",
    "newsletter.submit": "Subskrybuj",
    "newsletter.success": "Dziękujemy za subskrypcję naszego newslettera!",
    
    // Footer
    "footer.description": "Inteligentna automatyzacja, Blockchain i rozwiązania Web3 — budowanie przyszłości technologii biznesowej.",
    "footer.quicklinks": "Szybkie linki",
    "footer.home": "Strona główna",
    "footer.ecosystem": "Ekosystem",
    "footer.projects": "Projekty",
    "footer.contact": "Kontakt",
    "footer.legal": "Prawne",
    "footer.privacy": "Polityka prywatności",
    "footer.terms": "Warunki korzystania",
    "footer.copyright": "AI Byte Consult Ltd. Wszelkie prawa zastrzeżone.",
    
    // Telegram Products
    "products.badge": "Pakiety startowe",
    "products.title": "Rozwiązania Telegram",
    "products.subtitle": "Profesjonalne narzędzia Telegram do zwiększenia obecności biznesowej",
    "products.oneTime": "jednorazowo",
    "products.buyNow": "Kup teraz",
    "products.note": "Bezpieczna płatność przez Revolut. Dostawa w ciągu 1-3 dni roboczych.",
    
    "products.card.title": "Karta cyfrowa",
    "products.card.subtitle": "Wizytówka Telegram",
    "products.card.description": "Profesjonalny bot wizytówki cyfrowej prezentujący Twoje usługi, dane kontaktowe i linki społecznościowe.",
    "products.card.feature1": "Niestandardowy design marki",
    "products.card.feature2": "Kontakt i linki społecznościowe",
    "products.card.feature3": "Prezentacja usług",
    "products.card.feature4": "Łatwe udostępnianie przez link",
    
    "products.bot.title": "Bot Menu",
    "products.bot.subtitle": "Bot grupy Telegram",
    "products.bot.description": "Inteligentny bot dla Twojej grupy Telegram z interaktywnym menu i automatycznymi odpowiedziami.",
    "products.bot.feature1": "Interaktywny system menu",
    "products.bot.feature2": "Automatyczne wiadomości powitalne",
    "products.bot.feature3": "Podstawowe narzędzia moderacji",
    "products.bot.feature4": "Niestandardowe polecenia",
    
    "products.ai.title": "Asystent AI",
    "products.ai.subtitle": "Bot grupowy oparty na AI",
    "products.ai.description": "Inteligentny bot AI dla grup z katalogiem produktów i automatycznymi odpowiedziami.",
    "products.ai.feature1": "Odpowiedzi czatu oparte na AI",
    "products.ai.feature2": "Wyświetlanie katalogu produktów",
    "products.ai.feature3": "Obsługa zapytań o zamówienia",
    "products.ai.feature4": "Wsparcie wielojęzyczne",
  },
  tr: {
    // Header
    "nav.home": "Ana Sayfa",
    "nav.ecosystem": "Ekosistem",
    "nav.projects": "Projeler",
    "nav.automation": "Otomasyon",
    "nav.contact": "İletişim",
    
    // Hero
    "hero.title": "AI Byte Consult Ltd",
    "hero.subtitle": "Akıllı İş Sistemlerinin Geleceği",
    "hero.description": "Yapay zeka geliştirme ve iş otomasyonu konusunda uzmanlaşmış küresel bir teknoloji şirketi. İşletmeler, otelcilik, sağlık, lojistik ve araştırma için akıllı sistemler tasarlıyoruz — inovasyon yoluyla dünya çapında organizasyonları güçlendiriyoruz.",
    "hero.cta": "Ekosistemi Keşfet",
    
    // About
    "about.title": "Şirket Hakkında",
    "about.p1": "AI Byte Consult Ltd., yapay zeka ve otomasyonda uzmanlaşmış küresel bir teknoloji şirketidir. Operasyonları optimize eden, karar vermeyi geliştiren ve dünya çapındaki organizasyonlar için dijital dönüşümü hızlandıran akıllı sistemler tasarlıyoruz.",
    "about.p2": "Yapay zeka destekli çözümlerimiz çeşitli sektörlere hizmet vermektedir — B2B ve B2C işletmelerden otelcilik, sağlık, lojistik, jeoloji ve bilimsel araştırmaya kadar.",
    
    // Ecosystem
    "ecosystem.title": "Ekosistemimiz",
    "ecosystem.subtitle": "Modern dijital ekonomi için kapsamlı yapay zeka destekli çözümler paketi",
    "ecosystem.nics.title": "NICS AI Ekosistemi",
    "ecosystem.nics.desc": "NICS AI Ekosistemi, sektörleri birbirine bağlamak, iş akışlarını otomatikleştirmek ve platformlar arası veri senkronizasyonunu sağlamak için tasarlanmış birleşik bir yapay zeka ve blockchain altyapısıdır.",
    "ecosystem.horeca.title": "NICS AI HoReCa",
    "ecosystem.horeca.desc": "NICS AI HoReCa, restoranlar, barlar ve kafeler için gelişmiş bir yapay zeka otomasyon platformudur.",
    "ecosystem.geologist.title": "NICS AI Jeolog",
    "ecosystem.geologist.desc": "NICS AI Jeolog, jeolojiyi, madenciliği ve soy ağacını akıllı veri füzyonu ile birleştiren analitik bir platformdur.",
    "ecosystem.aquaterra.title": "AquaTerra World (Metaverse)",
    "ecosystem.aquaterra.desc": "AquaTerra World, sanal işbirliğini, eğlenceyi ve iş inovasyonunu bir araya getiren sürükleyici, yapay zeka destekli bir metaverse'dir.",
    "ecosystem.pantheon.title": "Ebedilerin Panteonu",
    "ecosystem.pantheon.desc": "Ebedilerin Panteonu AI, antik mitolojiden ilham alan interaktif iNFT varlıklarının devrim niteliğinde bir koleksiyonudur.",
    "ecosystem.pride.title": "PRIDE Sosyal Ağ",
    "ecosystem.pride.desc": "PRIDE Sosyal Ağ, yaratıcılığı ve katılımı yerel tokenlarla ödüllendiren merkezi olmayan bir Web3 topluluk platformudur.",
    
    // Projects
    "projects.title": "Çalışmalarımız",
    "projects.subtitle": "Geleceğe yönelik işletmeler için ölçülebilir sonuçlar sunan gerçek çözümler",
    "projects.restaurant.title": "Restoran Zinciri Otomasyonu",
    "projects.restaurant.desc": "TasteWave Bistro için akıllı sipariş ve yapay zeka müşteri hizmeti. Verimlilik %150 arttı.",
    "projects.logistics.title": "Lojistik Ayrıştırıcı AI",
    "projects.logistics.desc": "CargoNova için tahmine dayalı analitik ile gerçek zamanlı tedarik zinciri takibi.",
    "projects.hotel.title": "Otel Rezervasyon Otomasyonu",
    "projects.hotel.desc": "OceanView Resorts için sorunsuz rezervasyon deneyimi ile WhatsApp chatbot entegrasyonu.",
    "projects.nft.title": "NFT Zeka Çerçevesi",
    "projects.nft.desc": "Eternals by Nixie için ses sentezi ile yapay zeka tabanlı eser oluşturma sistemi.",
    "projects.clinic.title": "Klinikler İçin Sesli Asistan",
    "projects.clinic.desc": "MediCore Health için doğal dil işleme ile randevu otomasyonu.",
    "projects.retail.title": "Perakende Analitik Platformu",
    "projects.retail.desc": "UrbanMarket için envanter optimizasyonu ile yapay zeka destekli satış tahmini.",
    
    // Automation Constructor
    "constructor.title": "Otomasyon Yapıcısı",
    "constructor.subtitle": "Dakikalar içinde özel yapay zeka otomasyonunuzu tasarlayın — platformunuzu, modelinizi ve rolünüzü seçin.",
    "constructor.step1": "Platform Seç",
    "constructor.step2": "AI Modeli Seç",
    "constructor.step3": "Görevinizi Tanımlayın",
    "constructor.step4": "Otomasyon Türü Seç",
    "constructor.step5": "Entegrasyon Kurulumu",
    "constructor.step5.desc": "Yapay zeka otomasyonunuzun harici sistemlere nasıl bağlanacağını seçin.",
    "constructor.step6": "İncele ve Gönder",
    "constructor.task.placeholder": "Otomasyonunuzun ne yapması gerektiğini açıklayın...",
    "constructor.contact.title": "İletişim Bilgileri",
    "constructor.contact.desc": "Lütfen en az bir iletişim yöntemi girin:",
    "constructor.skip": "💡 Emin değil misiniz? Daha sonra seçin",
    "constructor.back": "Geri",
    "constructor.next": "İleri",
    "constructor.submit": "Siparişi Gönder",
    "constructor.success": "✅ İstek başarıyla gönderildi! Yakında sizinle iletişime geçeceğiz.",
    "constructor.error.platform": "Lütfen bir platform seçin",
    "constructor.error.model": "Lütfen bir AI modeli seçin",
    "constructor.error.task": "Lütfen görevinizi açıklayın",
    "constructor.error.role": "Lütfen otomasyon türünü seçin",
    "constructor.error.contact": "Lütfen en az bir iletişim yöntemi girin.",
    
    // AI Automation Fix
    "aifix.title": "AI Otomasyon Düzeltmesi",
    "aifix.subtitle": "Küresel Şirketler İçin Yapay Zeka Destekli İş Otomasyonu",
    "aifix.intro1": "AI ByteConsult Ltd, yapay zeka destekli iş otomasyonu, akıllı sistemler ve gelişmiş iş akışı otomasyonu konusunda uzmanlaşmış küresel bir teknoloji şirketidir.",
    "aifix.intro2": "Amiral gemisi çözümümüz AI Automation Fix, tek bir temel iş sürecini hızlı ve verimli bir şekilde otomatikleştirmek için tasarlanmıştır.",
    "aifix.included": "Neler Dahil",
    "aifix.included.1": "Hızlı otomasyon denetimi (20-30 dakika)",
    "aifix.included.2": "Yüksek etkili bir iş sürecinin otomasyonu",
    "aifix.included.3": "Yapay zeka destekli iş akışları ve sistem entegrasyonları",
    "aifix.included.4": "Dokümantasyon ve isteğe bağlı devam eden destek",
    "aifix.benefits": "İş Avantajları",
    "aifix.benefits.1": "Azaltılmış manuel iş yükü",
    "aifix.benefits.2": "Daha hızlı potansiyel müşteri ve müşteri yanıt süreleri",
    "aifix.benefits.3": "Geliştirilmiş operasyonel verimlilik",
    "aifix.benefits.4": "Ölçeklenebilir yapay zeka destekli süreçler",
    "aifix.pricing": "Örnek Fiyatlandırma",
    "aifix.pricing.audit": "Otomasyon Denetimi",
    "aifix.pricing.impl": "Uygulama",
    "aifix.pricing.support": "Aylık Destek",
    "aifix.usecases": "Tipik Otomasyon Kullanım Alanları",
    "aifix.usecase.lead": "AI Lead Handler",
    "aifix.usecase.lead.desc": "Alım, yeterlilik, yönlendirme",
    "aifix.usecase.sales": "AI Satış Asistanı",
    "aifix.usecase.sales.desc": "Potansiyel müşteri yeterliliği ve destek",
    "aifix.usecase.content": "AI İçerik Motoru",
    "aifix.usecase.content.desc": "Otomatik içerik iş akışları",
    "aifix.usecase.support": "AI Destek Ajanı",
    "aifix.usecase.support.desc": "7/24 müşteri yardımı",
    "aifix.usecase.owner": "AI Sahip Asistanı",
    "aifix.usecase.owner.desc": "Dahili özetler ve içgörüler",
    "aifix.howitworks": "Nasıl Çalışır",
    "aifix.step1": "İş akışınızı anlamak için keşif görüşmesi",
    "aifix.step2": "En yüksek etkili otomasyonun belirlenmesi",
    "aifix.step3": "AI, API'ler ve otomasyon platformları kullanılarak oluşturma ve dağıtım",
    "aifix.step4": "Teslimat, dokümantasyon ve isteğe bağlı destek",
    "aifix.cta.title": "İşinizi yapay zeka ile otomatikleştirmeye hazır mısınız?",
    "aifix.cta.subtitle": "Bir otomasyon denetimi ayırtın veya başlamak için ekibimizle iletişime geçin.",
    "aifix.cta.button": "Şimdi Başla",
    
    // Testimonials
    "testimonials.title": "Yenilikçiler Tarafından Güvenilir",
    "testimonials.subtitle": "Müşterilerimizin bizimle çalışma hakkında söylediklerini görün",
    "testimonials.1.quote": "AI Byte Consult lojistik operasyonlarımızda devrim yarattı. Gerçek zamanlı takip sistemi bize sayısız saat kazandırdı.",
    "testimonials.1.author": "Maria Lopez",
    "testimonials.1.position": "CEO, CargoNova",
    "testimonials.2.quote": "Otomasyon sistemleri restoran verimliliğimizi iki katına çıkardı.",
    "testimonials.2.author": "David Chen",
    "testimonials.2.position": "Kurucu, TasteWave Bistro",
    "testimonials.3.quote": "Yapay zeka katmanları sayesinde NFT lansmanımız gerçekten akıllı hale geldi.",
    "testimonials.3.author": "Elena Rossi",
    "testimonials.3.position": "NFT Proje Lideri",
    
    // Team
    "team.title": "Kurucularla Tanışın",
    "team.subtitle": "AI Byte Consult Ltd.'nin arkasındaki vizyonerler",
    "team.alex.name": "Alexander Lunin",
    "team.alex.role": "Kurucu Ortak ve AI Mimarı",
    "team.alex.bio": "Nixie Ekosistemi genelinde AI mimarisi ve Web3 entegrasyonlarını yönetiyor.",
    "team.aleksandr.name": "Aleksandr Tochilov",
    "team.aleksandr.role": "Kurucu Ortak ve Ürün Direktörü",
    "team.aleksandr.bio": "Otomasyon sistemleri, müşteri çözümleri ve yaratıcı ekosistem tasarımına odaklanıyor.",
    
    // Contact
    "contact.title": "İletişime Geçin",
    "contact.subtitle": "Otomasyonun geleceğini birlikte inşa edelim",
    "contact.name": "İsim",
    "contact.name.placeholder": "Adınız",
    "contact.email": "E-posta",
    "contact.email.placeholder": "email@ornek.com",
    "contact.message": "Mesaj",
    "contact.message.placeholder": "Projeniz hakkında bize bilgi verin...",
    "contact.submit": "Mesaj Gönder",
    "contact.success": "Mesaj gönderildi! Yakında size döneceğiz.",
    
    // Newsletter
    "newsletter.title": "Güncel Kalın",
    "newsletter.subtitle": "İnovasyon güncellemelerimize katılın ve yeni özelliklerden ilk siz haberdar olun",
    "newsletter.placeholder": "email@ornek.com",
    "newsletter.submit": "Abone Ol",
    "newsletter.success": "Bültenimize abone olduğunuz için teşekkürler!",
    
    // Footer
    "footer.description": "Akıllı Otomasyon, Blockchain ve Web3 Çözümleri — NICS AI Ekosistemi içinde iş teknolojisinin geleceğini inşa ediyoruz.",
    "footer.quicklinks": "Hızlı Bağlantılar",
    "footer.home": "Ana Sayfa",
    "footer.ecosystem": "Ekosistem",
    "footer.projects": "Projeler",
    "footer.contact": "İletişim",
    "footer.legal": "Yasal",
    "footer.privacy": "Gizlilik Politikası",
    "footer.terms": "Hizmet Şartları",
    "footer.copyright": "AI Byte Consult Ltd. Tüm hakları saklıdır.",
    
    // Telegram Products
    "products.badge": "Başlangıç Paketleri",
    "products.title": "Telegram Çözümleri",
    "products.subtitle": "İş varlığınızı artırmak için profesyonel Telegram araçları",
    "products.oneTime": "tek seferlik",
    "products.buyNow": "Şimdi Satın Al",
    "products.note": "Revolut üzerinden güvenli ödeme. 1-3 iş günü içinde teslimat.",
    
    "products.card.title": "Dijital Kart",
    "products.card.subtitle": "Telegram Kartvizit",
    "products.card.description": "Hizmetlerinizi, iletişim bilgilerinizi ve sosyal bağlantılarınızı sergileyen profesyonel dijital kartvizit botu.",
    "products.card.feature1": "Özel markalı tasarım",
    "products.card.feature2": "İletişim ve sosyal bağlantılar",
    "products.card.feature3": "Hizmet vitrini",
    "products.card.feature4": "Link ile kolay paylaşım",
    
    "products.bot.title": "Menü Botu",
    "products.bot.subtitle": "Telegram Grup Botu",
    "products.bot.description": "Telegram grubunuz için interaktif menü ve otomatik yanıtlar içeren akıllı bir bot.",
    "products.bot.feature1": "İnteraktif menü sistemi",
    "products.bot.feature2": "Otomatik hoş geldin mesajları",
    "products.bot.feature3": "Temel moderasyon araçları",
    "products.bot.feature4": "Özel komutlar",
    
    "products.ai.title": "AI Asistan",
    "products.ai.subtitle": "AI Destekli Grup Botu",
    "products.ai.description": "Ürün kataloğu ve akıllı yanıtlarla gruplar için akıllı bir AI botu.",
    "products.ai.feature1": "AI destekli sohbet yanıtları",
    "products.ai.feature2": "Ürün kataloğu görüntüleme",
    "products.ai.feature3": "Sipariş sorgulama işleme",
    "products.ai.feature4": "Çok dilli destek",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  const isRTL = language === "ar";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
